INSERT INTO VEHICLE (Vehicle_ID, Vehicle_Name, VType) VALUES 
(1, 'M1 Abrams', 'Main Battle Tank'),
(2, 'T-90', 'Main Battle Tank'),
(3, 'Challenger 2', 'Main Battle Tank'),
(4, 'Leopard 2', 'Main Battle Tank'),
(5, 'Type 99', 'Main Battle Tank'),
(6, 'M2 Bradley', 'Infantry Fighting Vehicle'),
(7, 'BMP-3', 'Infantry Fighting Vehicle'),
(8, 'Warrior', 'Infantry Fighting Vehicle'),
(9, 'K21', 'Infantry Fighting Vehicle'),
(10, 'Puma', 'Infantry Fighting Vehicle'),
(11, 'M113', 'Armored Personnel Carrier'),
(12, 'BTR-80', 'Armored Personnel Carrier'),
(13, 'LAV-25', 'Armored Personnel Carrier'),
(14, 'Pandur II', 'Armored Personnel Carrier'),
(15, 'VAB', 'Armored Personnel Carrier'),
(16, 'Humvee', 'Utility Vehicle'),
(17, 'LMTV', 'Utility Vehicle'),
(18, 'HMMWV', 'Utility Vehicle'),
(19, 'G-Wagon', 'Utility Vehicle'),
(20, 'Pinzgauer', 'Utility Vehicle'),
(21, 'AH-64 Apache', 'Attack Helicopter'),
(22, 'Mi-24 Hind', 'Attack Helicopter'),
(23, 'Tiger', 'Attack Helicopter'),
(24, 'Ka-52', 'Attack Helicopter'),
(25, 'AH-1Z Viper', 'Attack Helicopter'),
(26, 'F-35 Lightning II', 'Multirole Fighter'),
(27, 'Su-35', 'Multirole Fighter'),
(28, 'Eurofighter Typhoon', 'Multirole Fighter'),
(29, 'JAS 39 Gripen', 'Multirole Fighter'),
(30, 'Rafale', 'Multirole Fighter'),
(31, 'USS Nimitz', 'Aircraft Carrier'),
(32, 'HMS Queen Elizabeth', 'Aircraft Carrier'),
(33, 'INS Vikramaditya', 'Aircraft Carrier'),
(34, 'Liaoning', 'Aircraft Carrier'),
(35, 'Charles de Gaulle', 'Aircraft Carrier'),
(36, 'Ohio-class', 'Submarine'),
(37, 'Typhoon-class', 'Submarine'),
(38, 'Seawolf-class', 'Submarine'),
(39, 'Kilo-class', 'Submarine'),
(40, 'Los Angeles-class', 'Submarine'),
(41, 'MIM-104 Patriot', 'Surface-to-Air Missile System'),
(42, 'S-400 Triumf', 'Surface-to-Air Missile System'),
(43, 'HQ-9', 'Surface-to-Air Missile System'),
(44, 'Iron Dome', 'Surface-to-Air Missile System'),
(45, 'NASAMS', 'Surface-to-Air Missile System'),
(46, 'M270 MLRS', 'Multiple Launch Rocket System'),
(47, 'BM-21 Grad', 'Multiple Launch Rocket System'),
(48, 'TOS-1', 'Multiple Launch Rocket System'),
(49, 'Astros II', 'Multiple Launch Rocket System'),
(50, 'Pinaka', 'Multiple Launch Rocket System');

