INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (6, 'Major', 'AK-47', 150000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (7, 'Colonel', 'MP5', 200000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (8, 'Lieutenant', 'Glock 17', 500);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (9, 'Captain', 'Remington 700', 300000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (10, 'Commander', 'UMP45', 180000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (11, 'Major', 'SIG Sauer P226', 700);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (12, 'Colonel', 'Steyr AUG', 250000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (13, 'Lieutenant', 'FN SCAR', 400000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (14, 'Captain', 'HK416', 350000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (15, 'Commander', 'Barrett M82', 700000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (16, 'Major', 'Benelli M4', 200000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (17, 'Colonel', 'SPAS-12', 280000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (18, 'Lieutenant', 'FAMAS', 220000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (19, 'Captain', 'G36', 260000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (20, 'Commander', 'PP-19 Bizon', 150000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (21, 'Major', 'PPSh-41', 120000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (22, 'Colonel', 'SVD Dragunov', 450000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (23, 'Lieutenant', 'M60', 500000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (24, 'Captain', 'RPD', 550000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (25, 'Commander', 'MG42', 600000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (26, 'Major', 'AA-12', 450000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (27, 'Colonel', 'Negev', 650000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (28, 'Lieutenant', 'RPG-7', 800000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (29, 'Captain', 'AT4', 700000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (30, 'Commander', 'M203', 350000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (31, 'Major', 'LAW', 300000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (32, 'Colonel', 'FIM-92 Stinger', 900000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (33, 'Lieutenant', 'Mossberg 500', 180000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (34, 'Captain', 'FN FAL', 350000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (35, 'Commander', 'Stoner 63', 400000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (36, 'Major', 'IMI Galil', 300000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (37, 'Colonel', 'Heckler & Koch G3', 380000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (38, 'Lieutenant', 'TAR-21', 420000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (39, 'Captain', 'AS Val', 280000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (40, 'Commander', 'Dragunov SVU', 500000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (41, 'Major', 'Type 56', 150000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (42, 'Colonel', 'Spectre M4', 200000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (43, 'Lieutenant', 'IMI Uzi', 100000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (44, 'Captain', 'Walther PPK', 600);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (45, 'Commander', 'Mossberg 590', 220000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (46, 'Major', 'MP7', 230000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (47, 'Colonel', 'Remington 870', 280000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (48, 'Lieutenant', 'HK MP5K', 180000);
INSERT INTO Weapon (Weapon_ID, Soldier_Rank, Weapon_Name, Weapon_Price) VALUES (49, 'Captain', 'SPAS-15', 320000);

